on:
  - push

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Restore cached virtualenv
        uses: actions/cache/restore@v4
        with:
          key: venv-${{ runner.os }}-${{ hashFiles('uv.lock') }}
          path: .venv

      - name: Install uv
        uses: astral-sh/setup-uv@v4

      - name: Run pre-commit
        run: uv run pre-commit run --all-files

      - name: Saved cached virtualenv
        uses: actions/cache/save@v4
        if: always()
        with:
          key: venv-${{ runner.os }}-${{ hashFiles('uv.lock') }}
          path: .venv
